# Generated by Django 3.2 on 2021-05-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='macitem',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='input.project'),
        ),
    ]
