# Generated by Django 3.2 on 2021-05-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_macitem_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
