# Generated by Django 3.2 on 2021-05-05 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_auto_20210505_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='macitem',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
