# Generated by Django 3.2 on 2021-05-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0006_auto_20210506_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='item_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
