# Generated by Django 3.2 on 2021-05-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0009_item_project_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='macItem',
            new_name='Device',
        ),
    ]
