# Generated by Django 3.2.2 on 2021-05-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0011_auto_20210516_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
